name: wears
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  rxdart: ^0.16.7

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  # assets/graphics/logo.png
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/graphics/logo.png
    - assets/graphics/logo_color.png

    - assets/imgs/landing_bg.png
    - assets/imgs/suit1.png
    - assets/imgs/suit2.png
    - assets/imgs/suit3.png
    - assets/imgs/suit4.jpg
    - assets/imgs/landing_bg3.png
    - assets/imgs/shoe.png
    - assets/imgs/bag.png
    - assets/imgs/suits_bg.jpg
    - assets/imgs/watch.jpg
    - assets/imgs/tie.jpg
    
    - assets/icons/back_arrow.png
    - assets/icons/menu.png
    - assets/icons/close.png
    - assets/icons/logo_icon.png
    - assets/icons/search.png
    - assets/icons/cart.png
    - assets/icons/category.png
    - assets/icons/home.png
    - assets/icons/favorite.png
    - assets/icons/user.png

  fonts:
  - family: Antonio
    fonts:
      - asset: assets/fonts/Antonio-Regular.ttf
      - asset: assets/fonts/Antonio-Light.ttf
        weight: 200
 
      - asset: assets/fonts/Antonio-Bold.ttf
        weight: 700

      - asset: assets/fonts/Anton-Regular.ttf
        weight: 900


  - family: Raleway
    fonts:
      - asset: assets/fonts/Raleway-Regular.ttf
      - asset: assets/fonts/Raleway-Thin.ttf
        weight: 200
      - asset: assets/fonts/Raleway-Black.ttf
        weight: 900







  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
